Enhanced error reported when pyknx v1 is installed. When trying to run setup.py from Homewatcher while Pyknx version 1 is installed (most likely by mistake, because the --pre option was not passed to *pip install*), the error reported to the user was not clearly pointing out the cause: ``` Running setup.py (path:/tmp/pip_build_root/homewatcher/setup.py) egg_info for package homewatcher     Traceback (most recent call last):       File "<string>", line 17, in <module>       File "/tmp/pip_build_root/homewatcher/setup.py", line 26, in <module>         import homewatcher       File "homewatcher/__init__.py", line 23, in <module>         from pyknx import Version     ImportError: cannot import name Version     Complete output from command python setup.py egg_info:     Traceback (most recent call last):
  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/homewatcher/setup.py", line 26, in <module>

    import homewatcher

  File "homewatcher/__init__.py", line 23, in <module>

    from pyknx import Version

ImportError: cannot import name Version
```

The fix consist in importing ensurepyknx.py from homewatcher/__init__.py
to get a clear error.